# GitLab CI/CD 設定ファイル

# ステージ定義
stages:
  - build
  - test
  - security
  - deploy

# 共通設定
variables:
  # キャッシュの設定
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/Cypress"

# キャッシュ設定
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/
    - .cache/

# ビルドジョブ
build:
  stage: build
  image: node:20-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/
    expire_in: 1 hour
  only:
    - main
    - develop
    - merge_requests

# リンタージョブ
lint:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm run lint
    - npm run type-check
  needs: []
  only:
    - main
    - develop
    - merge_requests

# 単体テストジョブ
test:unit:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  needs: []
  only:
    - main
    - develop
    - merge_requests

# E2E テストジョブ
test:e2e:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  script:
    - npm ci
    - npx playwright install
    - npm run test:e2e
  artifacts:
    when: on_failure
    paths:
      - test-results/
    expire_in: 1 week
  needs: [build]
  only:
    - main
    - develop
    - merge_requests

# セキュリティ監査ジョブ
security:audit:
  stage: security
  image: node:20-alpine
  script:
    - npm audit --audit-level=moderate
  allow_failure: true
  needs: []
  only:
    - main
    - develop
    - merge_requests

# 依存関係の脆弱性スキャン
security:dependency-scanning:
  stage: security
  image: node:20-alpine
  script:
    - npm ci
    - npx snyk test --severity-threshold=high
  allow_failure: true
  needs: []
  only:
    - main
    - develop
  variables:
    SNYK_TOKEN: $SNYK_TOKEN

# コンテナイメージのビルド
docker:build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  needs: [build, test:unit]
  only:
    - main
    - develop

# ステージング環境へのデプロイ
deploy:staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $STAGING_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh $STAGING_USER@$STAGING_HOST << 'EOF'
        cd /var/www/app
        git pull origin develop
        npm install
        npm run build
        pm2 restart app
      EOF
  environment:
    name: staging
    url: https://staging.example.com
  needs: [build, test:unit, test:e2e]
  only:
    - develop

# 本番環境へのデプロイ
deploy:production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PRODUCTION_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh $PRODUCTION_USER@$PRODUCTION_HOST << 'EOF'
        cd /var/www/app
        git pull origin main
        npm install
        npm run build
        pm2 restart app
      EOF
  environment:
    name: production
    url: https://example.com
  needs: [build, test:unit, test:e2e, security:audit]
  only:
    - main
  when: manual # 手動承認が必要

# Kubernetes デプロイ例
deploy:k8s:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl set image deployment/app app=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - kubectl rollout status deployment/app
  environment:
    name: production
    url: https://example.com
  needs: [docker:build]
  only:
    - main
  when: manual

# ロールバックジョブ
rollback:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl rollout undo deployment/app
    - kubectl rollout status deployment/app
  environment:
    name: production
    url: https://example.com
  only:
    - main
  when: manual

# 通知ジョブ
notify:success:
  stage: .post
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - |
      curl -X POST $SLACK_WEBHOOK \
        -H 'Content-Type: application/json' \
        -d "{\"text\":\"✅ Pipeline succeeded for ${CI_COMMIT_REF_NAME} by ${GITLAB_USER_NAME}\"}"
  only:
    - main
    - develop
  when: on_success

notify:failure:
  stage: .post
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - |
      curl -X POST $SLACK_WEBHOOK \
        -H 'Content-Type: application/json' \
        -d "{\"text\":\"❌ Pipeline failed for ${CI_COMMIT_REF_NAME} by ${GITLAB_USER_NAME}\"}"
  only:
    - main
    - develop
  when: on_failure

# 言語別の設定例
#
# Python の場合:
# test:python:
#   image: python:3.11
#   script:
#     - pip install -r requirements.txt
#     - pytest --cov=src tests/
#     - coverage report
#
# Go の場合:
# test:go:
#   image: golang:1.21
#   script:
#     - go mod download
#     - go test ./...
#     - go build
#
# Java/Maven の場合:
# test:java:
#   image: maven:3.9-eclipse-temurin-17
#   script:
#     - mvn clean test
#     - mvn package
#
# Rust の場合:
# test:rust:
#   image: rust:latest
#   script:
#     - cargo build --release
#     - cargo test
